#!/bin/sh

set -e

if ! test $(which forever)
then
  echo
  echo "!!!!"
  echo "You don't have forever installed. You need to install it first."
  echo
  echo "Just install it with this command: "
  echo 'sudo npm install forever -g'
  echo
  exit 1
fi

npm install

echo "Finished setting up harmony-api! run it with script/server or install it with script/install."
